function [BatchInfo, STRDEF] = stl_load_batchinfo(bXLSLoad, strDataPath, ...
    xls_file, nTower, bPlotAll, bPlot_each_preform_on_subplot, ...
    bPlot_each_preform_on_subplot_with_inrangesubbatches_, loBFD, hiBFD , ...
    subbatchMinLen, subbatchMaxLen, x_columns, y_columns)
%STL_LOAD_BATCHINFO Wrapper around Brian's function that generates
%BatchInfo.
%   Simply calls Brian's function and retrieves the BatchInfo with the
%   given parameters.
[BatchInfo, STRDEF, ~, ~, ~, ~] = stl_load_parse_allt_function_rev4(...
                bXLSLoad, strDataPath, xls_file, nTower, bPlotAll, ...
                bPlot_each_preform_on_subplot, ...
                bPlot_each_preform_on_subplot_with_inrangesubbatches_, ...
                loBFD, hiBFD , subbatchMinLen, subbatchMaxLen, x_columns, ...
                y_columns);

